### ISSUE TITLE
test error when running locally

### ISSUE THREAD

**Issue by wyardley** [voxpupuli/puppet-nodejs#312] opened 2017-09-08 18:09 UTC
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: 5.1.0
- Ruby: 2.3.4p301
- Distribution: [running tests on Mac OS X]
- Module version: current git master

## How to reproduce (e.g Puppet code you use)
`bundle install`
`bundle exec rake test`

## What are you seeing
test failures [see below]. Tests don't appear to fail in Travis. Additionally, is the text "and install_options is a string" correct when it appears to be an array with a single string as the content? (`['--verbose']`)?

## What behaviour did you expect instead
tests to pass

## Output log
```
  1) Puppet::Type::Package::ProviderNpm when installing npm packages and install_options is a string passes the install_options to npm
     Failure/Error: npm('install', *options, package)
     
     Mocha::ExpectationError:
       unexpected invocation: Package[express](provider=npm).npm("install", "--global", "express")
       unsatisfied expectations:
       - expected exactly once, not yet invoked: Package[express](provider=npm).npm("install", "--global", "--verbose", "express")
       satisfied expectations:
       - allowed any number of times, not yet invoked: #<Puppet::Util::Feature:0x7faf8f99fd18>.root?(any_parameters)
       - allowed any number of times, not yet invoked: Puppet::Type::Package::ProviderNpm.command(:npm)
       - allowed any number of times, not yet invoked: Puppet::Type::Package::ProviderNpm.optional_commands(:npm)
     # ./lib/puppet/provider/package/npm.rb:76:in `install'
     # ./spec/unit/puppet/provider/package/npm_spec.rb:46:in `block (4 levels) in <top (required)>'

  2) Puppet::Type::Package::ProviderNpm when installing npm packages and install_options is a hash passes the install_options to npm
     Failure/Error: npm('install', *options, package)
     
     Mocha::ExpectationError:
       unexpected invocation: Package[express](provider=npm).npm("install", "--global", "express")
       unsatisfied expectations:
       - expected exactly once, not yet invoked: Package[express](provider=npm).npm("install", "--global", "--loglevel=error", "express")
       satisfied expectations:
       - allowed any number of times, not yet invoked: #<Puppet::Util::Feature:0x7faf8f99fd18>.root?(any_parameters)
       - allowed any number of times, not yet invoked: Puppet::Type::Package::ProviderNpm.command(:npm)
       - allowed any number of times, not yet invoked: Puppet::Type::Package::ProviderNpm.optional_commands(:npm)
     # ./lib/puppet/provider/package/npm.rb:76:in `install'
     # ./spec/unit/puppet/provider/package/npm_spec.rb:54:in `block (4 levels) in <top (required)>'

Finished in 0.43004 seconds (files took 7.12 seconds to load)
13 examples, 2 failures
```

**Comment by bastelfreak** [comment] 2017-09-09 22:00
I'm unable to reproduce this with ruby2.4.1 on archlinux. does it fail for you if you do bundle exec rake spec? This would do it sequentially, the test task does it in parallel

**Comment by wyardley** [comment] 2017-09-09 22:17
`bundle exec rake spec` doesn't seem to fail

and yet, if I run
`bundle exec rspec spec/unit/puppet/provider/package/npm_spec.rb`
it does fail. bundle and git are up to date.

I can also reproduce it with
```
% cd /tmp
% git clone git@github.com:voxpupuli/puppet-nodejs
% cd puppet-nodejs
% bundle install
% bundle exec rspec spec/unit/puppet/provider/package/npm_spec.rb
```
bundler itself is up to date.
I don't use rvm, so not so easy to test with a different Ruby version.

**Comment by wyardley** [comment] 2017-09-15 21:38
happens with parallel tests only, so I think it's an issue with the resource not getting reset or something
https://github.com/voxpupuli/puppet-nodejs/blob/master/spec/unit/puppet/provider/package/npm_spec.rb#L44-L45

**Comment by juniorsysadmin** [comment] 2018-12-02 02:33
Closing due to age, feel free to re-open.

**Closed by juniorsysadmin** 2018-12-02 02:33 UTC
Labels: needs-feedback, tests-fail
