### ISSUE TITLE
dependency cycle with v2.3.0

### ISSUE THREAD

**Issue by kwolf** [voxpupuli/puppet-nodejs#297] opened 2017-04-19 19:01 UTC
I'm getting a dependency cycle with v2.3.0 of the module.

```
Error: Failed to apply catalog: Found 1 dependency cycle:
(Anchor[apt_key 9FD3B784BC1C6FC31A8A0A1C1655A0AB68576280 present] => Apt::Key[Add key: 9FD3B784BC1C6FC31A8A0A1C1655A0AB68576280 from Apt::Source nodesource] => Apt::Source[nodesource] => Package[ca-certificates] => Apt::Source[nodesource] => Apt::Key[Add key: 9FD3B784BC1C6FC31A8A0A1C1655A0AB68576280 from Apt::Source nodesource] => Anchor[apt_key 9FD3B784BC1C6FC31A8A0A1C1655A0AB68576280 present])
```

This seems to happen with just a basic include of:

```puppet

class {'nodejs': }
```

This is on Ubuntu 14.04, Puppet 3.8.7, Ruby 1.8.7.  Anyone else seen this?

Removing the package requirements from the apt::source resolves it (not ideal, I know).

```puppet

  if ($ensure != 'absent') {
    apt::source { 'nodesource':
      include  => {
        'src' => $enable_src,
      },
      key      => {
        'id'     => '9FD3B784BC1C6FC31A8A0A1C1655A0AB68576280',
        'source' => 'https://deb.nodesource.com/gpgkey/nodesource.gpg.key',
      },
      location => "https://deb.nodesource.com/node_${url_suffix}",
      pin      => $pin,
      release  => $::lsbdistcodename,
      repos    => 'main',
#      require  => [
#       Package['apt-transport-https'],
#        Package['ca-certificates'],
#      ],
    }
```

**Comment by ffrank** [comment] 2017-05-01 21:06
Hi. Thanks for this report. It looks like a duplicate of #281 which we decided not to fix.

Can you confirm?

If so, I'm inclined to close this report as well, unless you have any new input on the discussion.

**Closed** 2017-09-24 06:34 UTC
Labels: wont-fix
