### ISSUE TITLE
Dependency cycle on ubuntu 14.04

### ISSUE THREAD

**Issue by pscadiz** [voxpupuli/puppet-nodejs#281] opened 2017-02-23 06:54 UTC
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: 3.8
- Ruby: 2.0.0
- Distribution: Ubuntu 14.04 (Trusty)
- Module version: (used latest commit)

## How to reproduce (e.g Puppet code you use)

```puppet
class { '::nodejs':
}
```

## What are you seeing
Puppet fails to run with a dependency cycle

## What behaviour did you expect instead
Node to be installed

## Output log
```
Error: Could not apply complete catalog: Found 1 dependency cycle
(Anchor[::nodejs::begin] => Class[Nodejs::Repo::Nodesource] => Class[Nodejs::Repo::Nodesource::Apt] => Apt::Source[nodesource] => Apt::Setting[list-nodesource] => File[/etc/apt/sources.list.d/nodesource.list] => Class[Apt::Update] => Exec[apt_update] => Class[Apt::Update] => Stage[setup] => Stage[main] => Class[Nodejs::Repo::Nodesource])
```

## Any additional information you'd like to impart
Running puppet on a docker container based on atlassian/bamboo-base-agent. Also updated puppetlabs-apt to tag 2.3.0

**Comment by zehzehpeh** [comment] 2017-03-03 20:54
:+1:
Confirmed on : 
- Puppet: 3.8.6
- Ruby: 2.3.1
- Distribution: Ubuntu 16.04 (Xenial)
- Module version: 2.3.0
- `puppetlabs-apt` at 2.3.0
- not running on a docker container
- also happens when using `repo_url_suffix => '6.x',`

**Comment by zehzehpeh** [comment] 2017-03-10 21:00
hey! Any update or ETA on this?

**Comment by bastelfreak** [comment] 2017-03-11 11:57
Hi @pscadiz and @zehzehpeh. Thanks for reporting this error. Is one of you able to provide a patch for this?

**Comment by zehzehpeh** [comment] 2017-03-14 19:52
@bastelfreak unfortunately I am not able to invest much time in this at the moment. However, I'd be more than happy to test any patch you send my way.

**Comment by ffrank** [comment] 2017-04-11 21:49
I'd love to see this fixed, but please note that Puppet 3.x is not supported by this module anymore. The issue appears to not be reproducible w/ Puppet 4.x.

Is a Puppet upgrade an option for you at all?

**Comment by zehzehpeh** [comment] 2017-04-18 15:46
>  Puppet 3.x is not supported by this module anymore.

Fair enough.

> Is a Puppet upgrade an option for you at all?

I am currently trying to confirm the issue is indeed because of Puppet 3.x by testing the same role in Puppet 4.x. If this is confirmed, the PR should be rejected. I will update this ticket and the PR accordingly.

**Comment by zehzehpeh** [comment] 2017-04-19 16:14
As commented [in the PR](https://github.com/voxpupuli/puppet-nodejs/pull/286#issuecomment-295327366), it seems the problem is indeed related to Puppet 3 vs 4.

**Comment by ffrank** [comment] 2017-04-19 16:48
Thanks for the feedback.

Closing this as WONTFIX.

**Closed by ffrank** 2017-04-19 16:48 UTC
Labels: bug
