### ISSUE TITLE
Does not install on Ubuntu 16.04.

### ISSUE THREAD

**Issue by frozenfoxx** [voxpupuli/puppet-nodejs#246] opened 2016-09-26 21:40 UTC
This module on Ubuntu 16.04 installs seems to only remove npm by default, not install it.  This does not seem to be expected behavior since [https://github.com/voxpupuli/puppet-nodejs/blob/master/manifests/params.pp#L69-L78](https://github.com/voxpupuli/puppet-nodejs/blob/master/manifests/params.pp#L69-L78) seems to indicate it should install by default.
### Affected Puppet, Ruby, OS and module versions/distributions
- Puppet:  4.7.0
- Ruby:  2.1.9p490
- Distribution:  Ubuntu 16.04
- Module version:  2.0.1
### How to reproduce (e.g Puppet code you use)

[https://github.com/frozenfoxx/puppet-hubot/blob/master/manifests/init.pp#L152-L157](https://github.com/frozenfoxx/puppet-hubot/blob/master/manifests/init.pp#L152-L157) on a Ubuntu 16.04 Puppet 4 system.
### What are you seeing

Module ensures npm is absent, removing the package if it was installed previously.
### What behaviour did you expect instead

Install the npm package.
### Output log

```
Notice: /Stage[main]/Nodejs::Install/Package[nodejs-dev]/ensure: removed
Notice: /Stage[main]/Nodejs::Install/Package[npm]/ensure: removed
Error: Could not update: Command npm is missing
Error: /Stage[main]/Hubot::Install/Package[hubot]/ensure: change from absent to 2.16.0 failed: Could not update: Command npm is missing
```
### Any additional information you'd like to impart

In further testing it looks like the GitHub code may be just fine, but the Forge version does not match the latest commits here.

**Comment by juniorsysadmin** [comment] 2016-09-27 10:52
Fixed by #242 , needs release

**Comment by cliff-wakefield** [comment] 2016-10-06 02:48
Still suffering the same issue even though I am using the latest commit, has this really been resolved?

**Comment by cliff-wakefield** [comment] 2016-10-06 11:42
Seems if I just let it install the latest from the default repos then it does work.

However if I specify `repo_url_suffix => '6.x'`, it doesn't.

**Comment by terrarum** [comment] 2016-11-20 14:41
I am having the exact same problem as @cliff-wakefield. Using puppet-nodejs 2.1.0, Ubuntu 16.04, Puppet  3.8.5.

**Comment by mxcoder** [comment] 2016-11-23 17:58
Try this:
```
class { 'nodejs' :
  repo_url_suffix => '6.x',
  nodejs_dev_package_ensure => 'absent',
  npm_package_ensure => 'absent',
}
```
The problem seems to be:
https://github.com/voxpupuli/puppet-nodejs/blob/master/manifests/params.pp#L80
https://github.com/voxpupuli/puppet-nodejs/blob/master/manifests/params.pp#L82

Because for xenial: https://deb.nodesource.com/node_6.x/dists/xenial/main/binary-amd64/Packages

```
Package: nodejs
Version: 6.9.1-1nodesource1~xenial1
Architecture: amd64
Maintainer: Chris Lea <chl@nodesource.com>
Installed-Size: 49558
Depends: libc6 (>= 2.15), libgcc1 (>= 1:3.4), libstdc++6 (>= 5.2)
Conflicts: nodejs-dev, nodejs-legacy, npm
Replaces: nodejs-dev (<= 0.8.22), nodejs-legacy, npm (<= 1.2.14)
Provides: nodejs-dev, nodejs-legacy, npm
```

**Comment by frozenfoxx** [comment] 2016-12-10 04:50
After PR [#261](https://github.com/voxpupuli/puppet-nodejs/pull/261) this has broken for me again.  On my 16.04 system now I am experiencing the same behavior as before, npm is getting removed automatically which makes it impossible to keep nodejs and npm installed.

**Comment by mxcoder** [comment] 2016-12-10 06:58
Hey @frozenfoxx sorry to hear about the issue, in theory using that suffix you're requesting this:

https://deb.nodesource.com/node_0.12/dists/xenial/main/binary-amd64/Packages
or
https://deb.nodesource.com/node_0.12/dists/xenial/main/binary-i386/Packages
(might want to view source, content-type is off)

And those also show:
```
Package: nodejs
Version: 0.12.17-1nodesource1~xenial1
Architecture: amd64
Maintainer: Jérémy Lal <kapouer@melix.org>
Installed-Size: 34412
Depends: libc6 (>= 2.15), libgcc1 (>= 1:3.4), libstdc++6 (>= 5.2), rlwrap
Conflicts: nodejs-dev, nodejs-legacy, npm
Replaces: nodejs-dev (<= 0.8.22), nodejs-legacy, npm (<= 1.2.14)
Provides: nodejs-dev, nodejs-legacy, npm
```
As you can see this repo provides a nodejs package that also `provides nodejs-dev, nodejs-legacy, npm` hence no need to force (using `present`) npm and nodejs-dev.

Not sure how else we can debug this, but maybe its some repo-level cache on your end? Or can you provide some debugging data? I think its important we correct this.

**Comment by frozenfoxx** [comment] 2017-05-15 05:25
I'm still running into this issue.  To test it I've been using Docker Ubuntu 16.04 containers, just telling it to install npm.  By the nature of the Docker container that's a fresh environment every time.

**Comment by zdavis** [comment] 2017-09-17 13:48
There does indeed seem to be an issue installing nodejs on ubuntu 16.04. Using this declaration:

  class { 'nodejs':
    repo_url_suffix => '6.x',
    nodejs_dev_package_ensure => 'absent',
    npm_package_ensure => 'absent'
  }

..on a fresh ubuntu 16.04 VM, I end up with circular symlinks:

/usr/bin/node > /usr/bin/nodejs
/usr/bin/nodejs > /etc/alternatives/nodejs
/etc/alternatives/nodejs > /usr/bin/node

If I then `apt-get remove nodejs` I get an error from the unresolvable symlinks. If I then manually remove the symlinks, remove nodejs with apt-get, and then reinstall it from the nodesource repo, iy installs correctly and works as expected. It seems there's something that this module is doing around creating those symlinks that's causing the problem.

**Comment by zdavis** [comment] 2017-09-17 13:56
Looks like it's caused by this:

https://github.com/voxpupuli/puppet-nodejs/blob/master/manifests/install.pp#L44

Node 6.x on Ubuntu 16 installs the actually node executable at /usr/bin/node and /usr/bin/nodejs is symlinked to /etc/alternatives/nodejs. The referenced line, above, symlinks /etc/alternatives/nodejs to /usr/bin/node, which creates the circular links.

If you're stuck on this, there is a workaround. Setting the `legacy_debian_symlinks` flag to false will prevent this module from making that symlink. This works for me:

```
  class { 'nodejs':
    repo_url_suffix => '6.x',
    legacy_debian_symlinks: false,
    nodejs_dev_package_ensure => 'absent',
    npm_package_ensure => 'absent'
  }
```

**Comment by zdavis** [comment] 2017-09-17 13:57
...same problem is identified and solved in #317

**Comment by bastelfreak** [comment] 2017-09-17 14:22
Hi @zdavis, I merged the PR #317, could you verify with our master branch if your errors are resolved?

**Comment by wyardley** [comment] 2017-09-17 15:08
Will #317 cause problems if package source is something other than the distribution ones (e.g., nodesource)? What if a user already has the older package installed and hasn't upgraded yet?

**Comment by wyardley** [comment] 2017-09-18 08:41
Noticed this when investigating this a little more:
`To run 'node' please ask your administrator to install the package 'nodejs-legacy'`
I think the right fix is to install `nodejs-legacy` package in certain-conditions (based on package source and / or os / nodejs version)

https://nodejs.org/en/download/package-manager/#debian-and-ubuntu-based-linux-distributions

```
root@ubuntu-server-1604-x64:~# apt-get install nodejs-legacy
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following NEW packages will be installed:
  nodejs-legacy
0 upgraded, 1 newly installed, 0 to remove and 188 not upgraded.
Need to get 27.7 kB of archives.
After this operation, 81.9 kB of additional disk space will be used.
Get:1 http://us.archive.ubuntu.com/ubuntu xenial-updates/universe amd64 nodejs-legacy all 4.2.6~dfsg-1ubuntu4.1 [27.7 kB]
Fetched 27.7 kB in 0s (62.1 kB/s)  
Selecting previously unselected package nodejs-legacy.
(Reading database ... 69869 files and directories currently installed.)
Preparing to unpack .../nodejs-legacy_4.2.6~dfsg-1ubuntu4.1_all.deb ...
Unpacking nodejs-legacy (4.2.6~dfsg-1ubuntu4.1) ...
Processing triggers for man-db (2.7.5-1) ...
Setting up nodejs-legacy (4.2.6~dfsg-1ubuntu4.1) ...
root@ubuntu-server-1604-x64:~# node
> root@ubuntu-server-1604-x64:~# node --version
v4.2.6
root@ubuntu-server-1604-x64:~# file /usr/bin/node
/usr/bin/node: symbolic link to nodejs
root@ubuntu-server-1604-x64:~# ls -al /usr/bin/node
lrwxrwxrwx 1 root root 6 May 20  2016 /usr/bin/node -> nodejs
```
I think this is probably cleaner, and also easier to work into some kind of logic for the module. Though it sounds like with the official packages, it's just a symlink too, so maybe not too harmful? But will the module break things if someone installs a very old node version that installs node as `/usr/bin/node`?

**Comment by wyardley** [comment] 2017-09-18 08:44
Since 'force' defaults to false (and isn't set), I guess it shouldn't cause a huge issue if a real `/usr/bin/node` gets installed.

**Comment by juniorsysadmin** [comment] 2017-09-19 07:13
Can/Should this issue be closed?

**Closed** 2017-09-19 17:05 UTC
Labels: bug, needs-feedback
